/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as PShareIdRouteImport } from './routes/p.$shareId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const PShareIdRoute = PShareIdRouteImport.update({
  id: '/p/$shareId',
  path: '/p/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/connections': typeof ConnectionsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/api/desk': typeof ApiDeskRoute
  '/p/$shareId': typeof PShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/connections': typeof ConnectionsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/api/desk': typeof ApiDeskRoute
  '/p/$shareId': typeof PShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/connections': typeof ConnectionsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/api/desk': typeof ApiDeskRoute
  '/p/$shareId': typeof PShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/checkout'
    | '/connections'
    | '/library'
    | '/login'
    | '/pricing'
    | '/studio'
    | '/api/desk'
    | '/p/$shareId'
    | '/api/auth/$'
    | '/api/billing/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/connections'
    | '/library'
    | '/login'
    | '/pricing'
    | '/studio'
    | '/api/desk'
    | '/p/$shareId'
    | '/api/auth/$'
    | '/api/billing/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/checkout'
    | '/connections'
    | '/library'
    | '/login'
    | '/pricing'
    | '/studio'
    | '/api/desk'
    | '/p/$shareId'
    | '/api/auth/$'
    | '/api/billing/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  ConnectionsRoute: typeof ConnectionsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  StudioRoute: typeof StudioRoute
  ApiDeskRoute: typeof ApiDeskRoute
  PShareIdRoute: typeof PShareIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareId': {
      id: '/p/$shareId'
      path: '/p/$shareId'
      fullPath: '/p/$shareId'
      preLoaderRoute: typeof PShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  ConnectionsRoute: ConnectionsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  StudioRoute: StudioRoute,
  ApiDeskRoute: ApiDeskRoute,
  PShareIdRoute: PShareIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
